//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_ASPxPivotGrid_v8_3 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_ASPxPivotGrid_v8_3() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxPivotGrid_v8_3", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Collapse].
        /// </summary>
        internal static string PivotGridStringId_Alt_Collapse {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocultar.
        /// </summary>
        internal static string PivotGridStringId_Alt_DragHideField {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_DragHideField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Expand].
        /// </summary>
        internal static string PivotGridStringId_Alt_Expand {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Filter].
        /// </summary>
        internal static string PivotGridStringId_Alt_FilterButton {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_FilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Filtered].
        /// </summary>
        internal static string PivotGridStringId_Alt_FilterButtonActive {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_FilterButtonActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Resize].
        /// </summary>
        internal static string PivotGridStringId_Alt_FilterWindowSizeGrip {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_FilterWindowSizeGrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ascending).
        /// </summary>
        internal static string PivotGridStringId_Alt_SortedAscending {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_SortedAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Descending).
        /// </summary>
        internal static string PivotGridStringId_Alt_SortedDescending {
            get {
                return ResourceManager.GetString("PivotGridStringId.Alt_SortedDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command cannot be used on multiple selections..
        /// </summary>
        internal static string PivotGridStringId_CannotCopyMultipleSelections {
            get {
                return ResourceManager.GetString("PivotGridStringId.CannotCopyMultipleSelections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string PivotGridStringId_CellError {
            get {
                return ResourceManager.GetString("PivotGridStringId.CellError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Area.
        /// </summary>
        internal static string PivotGridStringId_ColumnArea {
            get {
                return ResourceManager.GetString("PivotGridStringId.ColumnArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrastre la columna de campos aquí.
        /// </summary>
        internal static string PivotGridStringId_ColumnHeadersCustomization {
            get {
                return ResourceManager.GetString("PivotGridStringId.ColumnHeadersCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To.
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormAddTo {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormAddTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de campos de la tabla.
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormCaption {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag Items to the PivotGrid.
        /// </summary>
        internal static string PivotGridStringId_CustomizationFormText {
            get {
                return ResourceManager.GetString("PivotGridStringId.CustomizationFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Area.
        /// </summary>
        internal static string PivotGridStringId_DataArea {
            get {
                return ResourceManager.GetString("PivotGridStringId.DataArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string PivotGridStringId_DataFieldCaption {
            get {
                return ResourceManager.GetString("PivotGridStringId.DataFieldCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrastre los elementos de datos aquí.
        /// </summary>
        internal static string PivotGridStringId_DataHeadersCustomization {
            get {
                return ResourceManager.GetString("PivotGridStringId.DataHeadersCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Prefilter.
        /// </summary>
        internal static string PivotGridStringId_EditPrefilter {
            get {
                return ResourceManager.GetString("PivotGridStringId.EditPrefilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Area.
        /// </summary>
        internal static string PivotGridStringId_FilterArea {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string PivotGridStringId_FilterCancel {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrastre los campos de filtro aquí.
        /// </summary>
        internal static string PivotGridStringId_FilterHeadersCustomization {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterHeadersCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string PivotGridStringId_FilterOk {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Show All).
        /// </summary>
        internal static string PivotGridStringId_FilterShowAll {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Show Blanks).
        /// </summary>
        internal static string PivotGridStringId_FilterShowBlanks {
            get {
                return ResourceManager.GetString("PivotGridStringId.FilterShowBlanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gran Total.
        /// </summary>
        internal static string PivotGridStringId_GrandTotal {
            get {
                return ResourceManager.GetString("PivotGridStringId.GrandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details command cannot be executed when multiple items are selected in a report filter field. Select a single item for each field in the report filter area before performing a drillthrough..
        /// </summary>
        internal static string PivotGridStringId_OLAPDrillDownFilterException {
            get {
                return ResourceManager.GetString("PivotGridStringId.OLAPDrillDownFilterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measures.
        /// </summary>
        internal static string PivotGridStringId_OLAPMeasuresCaption {
            get {
                return ResourceManager.GetString("PivotGridStringId.OLAPMeasuresCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuCollapse {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuCollapseAll {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuCollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuExpand {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuExpandAll {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuFieldOrder {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuFieldOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocultar.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuHideField {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuHideField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocultar lista de campos.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuHideFieldList {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuHideFieldList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Prefilter.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuHidePrefilter {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuHidePrefilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Beginning.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuMovetoBeginning {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuMovetoBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to End.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuMovetoEnd {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuMovetoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Left.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuMovetoLeft {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuMovetoLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Right.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuMovetoRight {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuMovetoRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar Datos.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuRefreshData {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuRefreshData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All Sorting.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuRemoveAllSortByColumn {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuRemoveAllSortByColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar lista de campos.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuShowFieldList {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuShowFieldList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Prefilter.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuShowPrefilter {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuShowPrefilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort &quot;{0}&quot; by This Column.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuSortFieldByColumn {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuSortFieldByColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort &quot;{0}&quot; by This Row.
        /// </summary>
        internal static string PivotGridStringId_PopupMenuSortFieldByRow {
            get {
                return ResourceManager.GetString("PivotGridStringId.PopupMenuSortFieldByRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PivotGrid Prefilter.
        /// </summary>
        internal static string PivotGridStringId_PrefilterFormCaption {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrefilterFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Designer.
        /// </summary>
        internal static string PivotGridStringId_PrintDesigner {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerCategoryDefault {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerCategoryDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Values.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerCategoryFieldValues {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerCategoryFieldValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerCategoryHeaders {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerCategoryHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerCategoryLines {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerCategoryLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Headers.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerColumnHeaders {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerColumnHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Headers.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerDataHeaders {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerDataHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Headers.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerFilterHeaders {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerFilterHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers On Every Page.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerHeadersOnEveryPage {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerHeadersOnEveryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Lines.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerHorizontalLines {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerHorizontalLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Column Field Values.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerMergeColumnFieldValues {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerMergeColumnFieldValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Row Field Values.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerMergeRowFieldValues {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerMergeRowFieldValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerPageBehavior {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerPageBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerPageOptions {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerPageOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Headers.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerRowHeaders {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerRowHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused Filter Fields.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerUnusedFilterFields {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerUnusedFilterFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Print Appearance.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerUsePrintAppearance {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerUsePrintAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Lines.
        /// </summary>
        internal static string PivotGridStringId_PrintDesignerVerticalLines {
            get {
                return ResourceManager.GetString("PivotGridStringId.PrintDesignerVerticalLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Area.
        /// </summary>
        internal static string PivotGridStringId_RowArea {
            get {
                return ResourceManager.GetString("PivotGridStringId.RowArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrastre los campos de fila aquí.
        /// </summary>
        internal static string PivotGridStringId_RowHeadersCustomization {
            get {
                return ResourceManager.GetString("PivotGridStringId.RowHeadersCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        internal static string PivotGridStringId_StatusBad {
            get {
                return ResourceManager.GetString("PivotGridStringId.StatusBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        internal static string PivotGridStringId_StatusGood {
            get {
                return ResourceManager.GetString("PivotGridStringId.StatusGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        internal static string PivotGridStringId_StatusNeutral {
            get {
                return ResourceManager.GetString("PivotGridStringId.StatusNeutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string PivotGridStringId_TopValueOthersRow {
            get {
                return ResourceManager.GetString("PivotGridStringId.TopValueOthersRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string PivotGridStringId_Total {
            get {
                return ResourceManager.GetString("PivotGridStringId.Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Total.
        /// </summary>
        internal static string PivotGridStringId_TotalFormat {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Average.
        /// </summary>
        internal static string PivotGridStringId_TotalFormatAverage {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Count.
        /// </summary>
        internal static string PivotGridStringId_TotalFormatCount {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Custom.
        /// </summary>
        internal static string PivotGridStringId_TotalFormatCustom {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Max.
        /// </summary>
        internal static string PivotGridStringId_TotalFormatMax {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Min.
        /// </summary>
        internal static string PivotGridStringId_TotalFormatMin {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} StdDev.
        /// </summary>
        internal static string PivotGridStringId_TotalFormatStdDev {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatStdDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} StdDevp.
        /// </summary>
        internal static string PivotGridStringId_TotalFormatStdDevp {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatStdDevp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Sum.
        /// </summary>
        internal static string PivotGridStringId_TotalFormatSum {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Var.
        /// </summary>
        internal static string PivotGridStringId_TotalFormatVar {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Varp.
        /// </summary>
        internal static string PivotGridStringId_TotalFormatVarp {
            get {
                return ResourceManager.GetString("PivotGridStringId.TotalFormatVarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going Down.
        /// </summary>
        internal static string PivotGridStringId_TrendGoingDown {
            get {
                return ResourceManager.GetString("PivotGridStringId.TrendGoingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going Up.
        /// </summary>
        internal static string PivotGridStringId_TrendGoingUp {
            get {
                return ResourceManager.GetString("PivotGridStringId.TrendGoingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Change.
        /// </summary>
        internal static string PivotGridStringId_TrendNoChange {
            get {
                return ResourceManager.GetString("PivotGridStringId.TrendNoChange", resourceCulture);
            }
        }
    }
}
